# Generated by Django 3.1.2 on 2020-11-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.TextField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Currency volume')),
                ('weighted_price', models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='Weighted Price')),
                ('update_time', models.DateTimeField()),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market_data.coin')),
            ],
        ),
    ]
